"""Kerberos configuration for several realms at once.

``KRB5_CONFIG`` is read from the process environment, so it cannot be varied
per session — two administrators signed in to different domains share one
file. The file therefore accumulates a ``[realms]`` block per domain SAMFSCON
has been pointed at, and is rewritten whenever a new one appears.

Naming the KDC explicitly is what makes an IP address work: with
``dns_lookup_kdc`` alone, Kerberos would have to resolve SRV records for a
domain the container may know nothing about.

Writes are atomic (temporary file plus rename), so a session acquiring a
ticket never reads a half-written configuration.
"""

from __future__ import annotations

import logging
import os
import threading
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_TICKET_LIFETIME = "10h"
DEFAULT_RENEW_LIFETIME = "7d"


@dataclass(frozen=True)
class RealmEntry:
    realm: str
    kdcs: tuple[str, ...]

    def render(self) -> str:
        lines = [f"    {self.realm} = {{"]
        for kdc in self.kdcs:
            lines.append(f"        kdc = {kdc}")
        if self.kdcs:
            # The first KDC doubles as the password-change server; Samba DCs
            # serve kpasswd on the same host.
            lines.append(f"        admin_server = {self.kdcs[0]}")
        lines.append("    }")
        return "\n".join(lines)


class Krb5Configuration:
    """Maintains the krb5.conf shared by every session in this process."""

    def __init__(
        self,
        path: Path,
        *,
        ticket_lifetime: str = DEFAULT_TICKET_LIFETIME,
        renew_lifetime: str = DEFAULT_RENEW_LIFETIME,
        default_ccache_dir: Path | None = None,
    ) -> None:
        self.path = Path(path)
        self.ticket_lifetime = ticket_lifetime
        self.renew_lifetime = renew_lifetime
        self.default_ccache_dir = default_ccache_dir
        self._realms: dict[str, RealmEntry] = {}
        self._default_realm: str | None = None
        self._lock = threading.Lock()

    # -- public API --------------------------------------------------------

    def ensure_realm(self, realm: str, kdcs: tuple[str, ...] | list[str] = ()) -> None:
        """Make sure *realm* is present, with the given KDCs.

        Called before every ticket request. Rewrites the file only when
        something actually changed.
        """
        realm = realm.strip().upper()
        if not realm:
            return

        entry = RealmEntry(realm=realm, kdcs=tuple(dict.fromkeys(k for k in kdcs if k)))

        with self._lock:
            existing = self._realms.get(realm)
            if existing is not None and set(entry.kdcs) <= set(existing.kdcs):
                return  # nothing new to record

            if existing is not None:
                # Keep KDCs we already knew: a second session may have reached
                # the domain through a different address.
                merged = tuple(dict.fromkeys((*existing.kdcs, *entry.kdcs)))
                entry = RealmEntry(realm=realm, kdcs=merged)

            self._realms[realm] = entry
            if self._default_realm is None:
                self._default_realm = realm
            self._write()

        logger.info("krb5 realm registered: %s (kdc=%s)", realm, ", ".join(entry.kdcs) or "via DNS")

    def set_default_realm(self, realm: str) -> None:
        realm = realm.strip().upper()
        if not realm:
            return
        with self._lock:
            if self._default_realm == realm:
                return
            self._default_realm = realm
            if realm not in self._realms:
                self._realms[realm] = RealmEntry(realm=realm, kdcs=())
            self._write()

    def known_realms(self) -> list[str]:
        return sorted(self._realms)

    def environment(self) -> dict[str, str]:
        """Environment additions for a subprocess such as kinit."""
        return {"KRB5_CONFIG": str(self.path)}

    def apply_to_process(self) -> None:
        """Point this process's Kerberos library at our file.

        The Samba bindings read KRB5_CONFIG from the environment when they
        acquire a ticket, so it has to be set here rather than passed in.
        """
        os.environ["KRB5_CONFIG"] = str(self.path)

    # -- rendering ---------------------------------------------------------

    def render(self) -> str:
        lines = [
            "# Generated by SAMFSCON. Edits are overwritten.",
            "[libdefaults]",
        ]
        if self._default_realm:
            lines.append(f"    default_realm = {self._default_realm}")
        lines.extend(
            [
                "    dns_lookup_realm = false",
                # Still useful as a fallback for realms reached by name.
                "    dns_lookup_kdc = true",
                "    rdns = false",
                "    forwardable = true",
                "    renewable = true",
                f"    ticket_lifetime = {self.ticket_lifetime}",
                f"    renew_lifetime = {self.renew_lifetime}",
            ]
        )
        if self.default_ccache_dir is not None:
            lines.append(f"    default_ccache_name = FILE:{self.default_ccache_dir}/default")

        if self._realms:
            lines.append("")
            lines.append("[realms]")
            for realm in sorted(self._realms):
                lines.append(self._realms[realm].render())

            lines.append("")
            lines.append("[domain_realm]")
            for realm in sorted(self._realms):
                lower = realm.lower()
                lines.append(f"    .{lower} = {realm}")
                lines.append(f"    {lower} = {realm}")

        return "\n".join(lines) + "\n"

    def _write(self) -> None:
        content = self.render()
        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            # Atomic replace: a session reading the file mid-update would
            # otherwise see a truncated configuration.
            temporary = self.path.with_suffix(f".tmp.{os.getpid()}")
            temporary.write_text(content, encoding="utf-8")
            temporary.replace(self.path)
        except OSError as exc:
            logger.error("cannot write %s: %s", self.path, exc)
            return
        self.apply_to_process()


_configuration: Krb5Configuration | None = None
_configuration_lock = threading.Lock()


def get_krb5_configuration() -> Krb5Configuration:
    global _configuration
    with _configuration_lock:
        if _configuration is None:
            from samfscon.config import get_settings

            settings = get_settings()
            _configuration = Krb5Configuration(
                settings.krb5_config,
                default_ccache_dir=settings.ccache_dir,
            )
            # A configured default realm should be usable from the first
            # request, before anyone signs in.
            if settings.realm:
                _configuration.ensure_realm(settings.realm, tuple(settings.dc_hosts))
                _configuration.set_default_realm(settings.realm)
        return _configuration


def reset_krb5_configuration() -> None:
    """Test hook."""
    global _configuration
    with _configuration_lock:
        _configuration = None
